### ISSUE TITLE
[Question] Using a `Parser` as a `Producer` transformer

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Pipes-Parse-Library#40]
Hello! Question: I've found this function useful...

```haskell
-- Transform a producer of 'a' into a producer of 'b' using a parser that 
-- parses a 'b' out of a stream of 'a'.

go :: Parser a m b -> (Producer a m r -> Producer b m r)
go parser producer = do
  (b, producer') <- lift (runStateT parser producer)
  yield b
  go parser producer'
```

but I couldn't figure out how to write it at a high level, i.e. without `runStateT` and manual recursion. Is there a more idiomatic way?

**Comment by Gabriel439** [comment]
Does `Pipes.Parse.parsed_` do what you want?

http://hackage.haskell.org/package/pipes-parse-3.0.8/docs/Pipes-Parse.html#v:parsed_

**Comment by mitchellwrosen** [comment]
Yes it does, that's what I ended up using. Thanks.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
