### ISSUE TITLE
Why is parseForever deprecated?

### ISSUE THREAD

**Issue by chris-martin** [Gabriel439/Haskell-Pipes-Parse-Library#41]
`parseForever` seems like a very sensible function, and its deprecation makes me concerned that I don't understand something about pipes. Is it deprecated because it doesn't work properly? Is turning a parser into a `Pipe` not a good thing to do in general, or is the problem specific to the `Parser` type in this library?

**Comment by Gabriel439** [comment]
It's because the `parsed` function is more general and provides the ability to handle termination of the upstream input.  The `parseForever` function is unable to do that, which is why the deprecation message says to prefer the `parsed` function instead
